export const APP_CATEGORIES = [
  "Health & Fitness",
  "Food & Drink",
  "Productivity",
  "Finance",
  "Education",
  "Entertainment",
  "Social Networking",
  "Photo & Video",
  "Music",
  "Travel",
  "Navigation",
  "News",
  "Shopping",
  "Lifestyle",
  "Business",
  "Utilities",
  "Games",
  "Medical",
  "Books",
  "Reference",
  "Sports",
  "Weather",
] as const;

export const AUDIENCE_SUGGESTIONS: Record<string, string[]> = {
  "Health & Fitness": [
    "Endurance cyclists",
    "Marathon runners",
    "Yoga beginners",
    "Gym-goers tracking macros",
    "Meditation practitioners",
    "Home workout enthusiasts",
    "Swimmers logging laps",
    "Hikers tracking trails",
  ],
  "Food & Drink": [
    "Busy home cooks",
    "Vegan meal planners",
    "Wine enthusiasts",
    "Coffee aficionados",
    "Restaurant discovery seekers",
    "Meal prep beginners",
    "Baking hobbyists",
    "Calorie counters",
  ],
  "Productivity": [
    "Remote knowledge workers",
    "Students managing deadlines",
    "Freelancers tracking time",
    "Executives organizing tasks",
    "Writers outlining projects",
    "Developers managing sprints",
    "Parents coordinating schedules",
    "Entrepreneurs building habits",
  ],
  "Finance": [
    "First-time investors",
    "Budget-conscious families",
    "Freelancers managing invoices",
    "Crypto-curious beginners",
    "Debt payoff planners",
    "Small business owners",
    "Retirement savers",
    "Expense-tracking professionals",
  ],
  "Education": [
    "K-12 teachers",
    "University students",
    "Language learners",
    "Coding bootcamp students",
    "Homeschooling parents",
    "Lifelong learners",
    "Exam prep candidates",
    "Music students",
  ],
  "Entertainment": [
    "Movie buffs",
    "Podcast listeners",
    "Trivia fans",
    "Streaming series binge-watchers",
    "Board game enthusiasts",
    "Comedy lovers",
    "Documentary watchers",
    "Karaoke singers",
  ],
  "Social Networking": [
    "Local community organizers",
    "Niche hobby groups",
    "Content creators",
    "Event planners",
    "Alumni networks",
    "Makers and crafters",
    "Gamers finding squads",
    "Volunteer coordinators",
  ],
  "Photo & Video": [
    "Smartphone photographers",
    "Vloggers and content creators",
    "Wedding videographers",
    "Travel photographers",
    "Instagram influencers",
    "Filmmaking students",
    "Drone photography enthusiasts",
    "Photo editing hobbyists",
  ],
  "Music": [
    "Indie music discovery fans",
    "Amateur guitarists",
    "DJ hobbyists",
    "Concert-goers",
    "Playlist curators",
    "Aspiring producers",
    "Music theory learners",
    "Vinyl collectors",
  ],
  "Travel": [
    "Backpackers on a budget",
    "Business travelers",
    "Family vacation planners",
    "Solo female travelers",
    "Digital nomads",
    "Road trip enthusiasts",
    "Luxury travelers",
    "Adventure travel seekers",
  ],
  "Navigation": [
    "Daily commuters",
    "City cyclists",
    "Road trip drivers",
    "Public transit users",
    "Off-road explorers",
    "Walking tour participants",
    "Delivery drivers",
    "Boaters and sailors",
  ],
  "News": [
    "Tech news followers",
    "Financial market watchers",
    "Local news readers",
    "Politics enthusiasts",
    "Science news fans",
    "Sports score trackers",
    "Climate news followers",
    "Entertainment gossip readers",
  ],
  "Shopping": [
    "Deal hunters",
    "Fashion enthusiasts",
    "Vintage and thrift shoppers",
    "Sustainable product buyers",
    "Gift shoppers",
    "Sneaker collectors",
    "Home decor shoppers",
    "Coupon clippers",
  ],
  "Lifestyle": [
    "Journaling practitioners",
    "Minimalism adopters",
    "Self-improvement seekers",
    "Plant care enthusiasts",
    "Pet owners",
    "Gardeners",
    "Astrology followers",
    "Home organization fans",
  ],
  "Business": [
    "Startup founders",
    "Sales professionals",
    "Marketing managers",
    "HR recruiters",
    "Project managers",
    "Consultants",
    "Real estate agents",
    "Customer success teams",
  ],
  "Utilities": [
    "Power users",
    "IT administrators",
    "Privacy-conscious users",
    "File organizers",
    "Password managers seekers",
    "Network diagnostic users",
    "Scan and document users",
    "QR code users",
  ],
  "Games": [
    "Casual puzzle gamers",
    "Hardcore mobile gamers",
    "Strategy game fans",
    "Word game lovers",
    "RPG enthusiasts",
    "Multiplayer shooter fans",
    "Card game players",
    "Trivia and quiz gamers",
  ],
  "Medical": [
    "Patients managing chronic conditions",
    "Healthcare professionals",
    "Caregivers",
    "Mental health tracking users",
    "Pharmacy customers",
    "Telemedicine patients",
    "Symptom checkers",
    "Medical students",
  ],
  "Books": [
    "Avid readers",
    "Audiobook listeners",
    "Book club members",
    "Self-help book readers",
    "Fiction enthusiasts",
    "Non-fiction learners",
    "Indie author supporters",
    "Textbook readers",
  ],
  "Reference": [
    "Researchers",
    "Students writing papers",
    "Fact-checkers",
    "Dictionary and thesaurus users",
    "Encyclopedia readers",
    "Quote collectors",
    "Citation managers",
    "Wikipedia browsers",
  ],
  "Sports": [
    "Football fans",
    "Basketball followers",
    "Cricket enthusiasts",
    "Tennis players",
    "Soccer supporters",
    "Baseball stats lovers",
    "Golfers tracking rounds",
    "Fantasy sports players",
  ],
  "Weather": [
    "Outdoor event planners",
    "Farmers and growers",
    "Photographers chasing light",
    "Sailors and boaters",
    "Skiers tracking snow",
    "Travelers checking forecasts",
    "Pilots",
    "Storm chasers",
  ],
};

export function getAudienceSuggestions(category: string): string[] {
  return AUDIENCE_SUGGESTIONS[category] ?? [];
}